# Generated by Django 3.0.6 on 2022-05-29 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMS_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
